'use strict';
const $=s=>document.querySelector(s), NS='http://www.w3.org/2000/svg', KEY='terarium-v1';
const initial=()=>({name:'Moss',born:Date.now(),updated:Date.now(),hunger:80,happy:75,moisture:70,night:false,visits:0,decor:[{type:'fern',x:340,y:398},{type:'fern',x:657,y:399},{type:'mushroom',x:395,y:402},{type:'rock',x:605,y:410},{type:'flower',x:710,y:413}]});
let state=initial();try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved&&Array.isArray(saved.decor)&&Number.isFinite(saved.updated))state={...state,...saved};}catch{}
const elapsed=Math.max(0,Date.now()-state.updated)/3600000;for(const [k,rate]of [['hunger',2],['happy',1],['moisture',1.5]])state[k]=Math.max(15,Math.min(100,(Number(state[k])||70)-Math.min(elapsed,48)*rate));state.visits++;let selected=null, bubbleTimer, rainTimer;
function save(){state.updated=Date.now();try{localStorage.setItem(KEY,JSON.stringify(state));}catch{$('#personality').textContent='Storage unavailable. Enjoy this garden for now.';}}
function speak(msg){clearTimeout(bubbleTimer);$('#bubble').textContent=msg;$('#bubble').style.opacity=1;bubbleTimer=setTimeout(()=>$('#bubble').style.opacity=0,4200);}
function render(){ $('#name').textContent=state.name;for(const k of ['hunger','happy','moisture']){$('#'+k).value=state[k];$('#'+k+'-text').textContent=Math.round(state[k])+'%';}document.body.classList.toggle('night',state.night);$('#night').textContent=state.night?'☀ Daybreak':'☾ Nightfall';$('#night').setAttribute('aria-pressed',String(state.night));$('#age').textContent='DAY '+String(Math.max(1,Math.floor((Date.now()-state.born)/86400000)+1)).padStart(2,'0');$('#weather').textContent=state.night?'The world is getting sleepy':'A perfectly ordinary afternoon';$('#mood').textContent=state.hunger<35?'Could use a snack':state.happy>85?'Feeling very loved':'Feeling curious';$('#personality').textContent=state.visits>5?'Getting quite attached to you.':'Small creature. Big feelings.';}
function plant(d){const g=document.createElementNS(NS,'g');g.setAttribute('transform',`translate(${d.x} ${d.y})`);const shapes={fern:'<g class="plant"><path d="M0 0Q-7-55 0-120" stroke="#477748" stroke-width="4" fill="none"/><path d="M0-20Q-63-15-55-65Q-8-68 0-20M0-42Q53-30 56-81Q10-79 0-42M0-65Q-53-62-40-105Q-6-106 0-65M0-88Q40-72 37-120Q9-115 0-88M0-108Q-20-113-6-139Q10-127 0-108" fill="#5a884e"/><path d="M-30 0Q-57-37-74-46Q-88-3-30 0" fill="#85a352"/></g>',flower:'<g class="plant"><path d="M0 0Q-15-32 0-65" stroke="#6e8f43" stroke-width="4" fill="none"/><path d="M-5-22Q-36-45-37-17Q-15-3-5-22" fill="#7e9c50"/><g transform="translate(0 -65)" fill="#f8ead0"><ellipse cy="-13" rx="9" ry="16"/><ellipse cy="13" rx="9" ry="16"/><ellipse cx="-13" rx="16" ry="9"/><ellipse cx="13" rx="16" ry="9"/><circle r="9" fill="#d9b958"/></g></g>',mushroom:'<path d="M-6 0L-4-33H6L8 0" fill="#ebd9b3"/><path d="M-27-28Q-24-64 0-62Q24-64 27-28Z" fill="#b76f4c"/><circle cx="-10" cy="-42" r="4" fill="#f5dfba"/><circle cx="9" cy="-48" r="5" fill="#f5dfba"/>',rock:'<path d="M-29 0Q-33-14-16-22Q2-34 21-21Q34-12 31 0Z" fill="#aaa99a"/><path d="M-16-22L-3-9L21-21" stroke="#c9c8b7" stroke-width="2" fill="none"/>'};g.innerHTML=shapes[d.type]||shapes.fern;$('#decorations').append(g);}
function redraw(){ $('#decorations').replaceChildren();state.decor.forEach(plant);}
function celebrate(){ $('#pet').classList.remove('celebrate');void $('#pet').getBoundingClientRect();$('#pet').classList.add('celebrate');}
$('#pet').setAttribute('transform','translate(500 392)');
$('#pet-target').onclick=e=>{e.stopPropagation();if(selected){speak('Plant around me, please. I need leg room.');return;}state.happy=Math.min(100,state.happy+8);speak(['You have excellent head-patting technique.','I grew this leaf myself.','This is my favourite part of the internet.','A tiny hug for a tiny creature.'][Math.floor(Math.random()*4)]);celebrate();save();render();};
$('#feed').onclick=()=>{if(state.hunger>=98){speak('Full. Extremely full. Leaf me be.');return;}state.hunger=Math.min(100,state.hunger+18);state.happy=Math.min(100,state.happy+4);speak('A crumb! For me? What a day.');celebrate();save();render();};
$('#water').onclick=()=>{state.moisture=Math.min(100,state.moisture+20);speak('Rain smells like a fresh start.');clearInterval(rainTimer);let n=0;rainTimer=setInterval(()=>{const rain=$('#rain');rain.innerHTML=Array.from({length:22},()=>`<path d="M${260+Math.random()*470} ${130+Math.random()*250}l-4 13" stroke="#8baebb" stroke-width="2" opacity=".6"/>`).join('');if(++n>14){clearInterval(rainTimer);rain.replaceChildren();}},120);save();render();};
$('#night').onclick=()=>{state.night=!state.night;speak(state.night?'Goodnight, enormous person.':'Oh! You brought the sun back.');save();render();};
$('#decorate').onclick=()=>{const open=$('#shelf').hidden;$('#shelf').hidden=!open;$('#decorate').setAttribute('aria-expanded',String(open));if(!open){selected=null;$('.habitat').style.cursor='';document.querySelectorAll('[data-item]').forEach(b=>b.classList.remove('selected'));}};
document.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{selected=b.dataset.item;document.querySelectorAll('[data-item]').forEach(x=>x.classList.toggle('selected',x===b));$('.habitat').style.cursor='crosshair';speak('Pick a spot beside me.');});
$('#garden').setAttribute('tabindex','0');$('#garden').setAttribute('aria-label','Glass garden. Select a plant from the shelf, then press Enter here to plant it.');
$('#garden').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&selected){e.preventDefault();if(state.decor.length>=25){speak('Our jungle is full. Remove one to plant more.');return;}state.decor.push({type:selected,x:280+Math.random()*440,y:405});redraw();state.happy=Math.min(100,state.happy+3);save();render();speak('A new neighbour. Lovely.');}});
$('#garden').onclick=e=>{if(!selected)return;if(state.decor.length>=25){speak('We have a whole jungle. Remove one to plant more.');return;}const p=$('#garden').createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform($('#garden').getScreenCTM().inverse());if(q.x<250||q.x>750||q.y<190||q.y>455){speak('Try a spot inside the glass.');return;}state.decor.push({type:selected,x:q.x,y:400+(q.x-500)*.025});redraw();state.happy=Math.min(100,state.happy+3);save();render();speak('A new neighbour. Lovely.');};
$('#undo').onclick=()=>{state.decor.pop();redraw();save();};
$('#rename').onclick=()=>{$('#new-name').value=state.name;$('#naming').showModal();};$('#naming').addEventListener('close',()=>{if($('#naming').returnValue==='save'){state.name=$('#new-name').value.trim().slice(0,24)||'Moss';save();render();speak('That sounds like me.');}});
$('#reset').onclick=()=>{if(!confirm('Start a fresh garden? Your current creature and plants will be replaced.'))return;state=initial();save();redraw();render();speak('Oh, hello there.');};
setInterval(()=>{for(const k of ['hunger','happy','moisture'])state[k]=Math.max(15,state[k]-.1);save();render();},60000);
redraw();render();save();speak(state.visits>1?'You came back. I kept your spot.':'Oh, hello there.');
